# Generated by Django 5.0.9 on 2025-10-07 11:02

import MASTER.branches.models
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmbeddingModel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branches', to=settings.AUTH_USER_MODEL)),
                ('embedding_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='EmbeddingModel.embeddingmodel')),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'owner']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='branches/%Y/%m/', validators=[MASTER.branches.models.validate_file_size])),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('csv', 'CSV'), ('xml', 'XML'), ('json', 'JSON'), ('docx', 'Word')], max_length=10)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('chunks_count', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='branches.branch')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch Document',
                'verbose_name_plural': 'Branch Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(dimensions=3072)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='branches.branch')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='branches.branchdocument')),
                ('embedding_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_embeddings', to='EmbeddingModel.embeddingmodel')),
            ],
            options={
                'verbose_name': 'Branch Embedding',
                'verbose_name_plural': 'Branch Embeddings',
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['slug'], name='branches_br_slug_91f057_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_active'], name='branches_br_is_acti_22f294_idx'),
        ),
        migrations.AddIndex(
            model_name='branchdocument',
            index=models.Index(fields=['branch', 'is_processed'], name='branches_br_branch__9800f4_idx'),
        ),
        migrations.AddIndex(
            model_name='branchembedding',
            index=models.Index(fields=['branch'], name='branches_br_branch__ac3b14_idx'),
        ),
        migrations.AddIndex(
            model_name='branchembedding',
            index=models.Index(fields=['embedding_model'], name='branches_br_embeddi_e0ed96_idx'),
        ),
    ]
