# Generated by Django 5.0.9 on 2025-10-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchdocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
