from typing import Any, Iterable, Sequence


class Env:
    def __init__(self, **schema: Any) -> None: ...

    def read_env(self, path: Any = ..., recurse: bool = ...) -> None: ...

    def __call__(self, key: str, default: Any = ...) -> Any: ...

    def bool(self, key: str, default: bool = ...) -> bool: ...

    def int(self, key: str, default: int = ...) -> int: ...

    def list(self, key: str, cast: Any = ..., default: Sequence[str] = ...) -> list[str]: ...

    def json(self, key: str, default: Any = ...) -> Any: ...

    def db_url(self, key: str = ..., default: Any = ...) -> Any: ...

    def cache_url(self, key: str = ..., default: Any = ...) -> Any: ...


