# Generated by Django 5.0.9 on 2025-10-07 11:02

import MASTER.specializations.models
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmbeddingModel', '0001_initial'),
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_specializations', to=settings.AUTH_USER_MODEL)),
                ('embedding_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specializations', to='EmbeddingModel.embeddingmodel')),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'owner']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_specializations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpecializationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='specializations/%Y/%m/', validators=[MASTER.specializations.models.validate_file_size])),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('csv', 'CSV'), ('xml', 'XML'), ('json', 'JSON'), ('docx', 'Word')], max_length=10)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('chunks_count', models.IntegerField(default=0)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='specializations.specialization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Specialization Document',
                'verbose_name_plural': 'Specialization Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecializationEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(dimensions=3072)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='specializations.specializationdocument')),
                ('embedding_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialization_embeddings', to='EmbeddingModel.embeddingmodel')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='specializations.specialization')),
            ],
            options={
                'verbose_name': 'Specialization Embedding',
                'verbose_name_plural': 'Specialization Embeddings',
            },
        ),
        migrations.AddIndex(
            model_name='specialization',
            index=models.Index(fields=['branch', 'slug'], name='specializat_branch__0fc719_idx'),
        ),
        migrations.AddIndex(
            model_name='specialization',
            index=models.Index(fields=['is_active'], name='specializat_is_acti_afcd97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='specialization',
            unique_together={('branch', 'slug')},
        ),
        migrations.AddIndex(
            model_name='specializationdocument',
            index=models.Index(fields=['specialization', 'is_processed'], name='specializat_special_127957_idx'),
        ),
        migrations.AddIndex(
            model_name='specializationembedding',
            index=models.Index(fields=['specialization'], name='specializat_special_809d43_idx'),
        ),
        migrations.AddIndex(
            model_name='specializationembedding',
            index=models.Index(fields=['embedding_model'], name='specializat_embeddi_ee0674_idx'),
        ),
    ]
