# Generated by Django 5.0.9 on 2025-10-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '0003_add_vector_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='custom_system_prompt',
            field=models.TextField(blank=True, help_text='Custom system prompt for this specialization. Leave empty to use branch default.'),
        ),
    ]
