# Generated by Django 5.2.6 on 2025-10-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('huggingface', 'HuggingFace'), ('cohere', 'Cohere')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('dimensions', models.IntegerField()),
                ('cost_per_1k_tokens', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Embedding Model',
                'verbose_name_plural': 'Embedding Models',
                'ordering': ['provider', 'name'],
            },
        ),
    ]
