# Generated by Django 5.0.9 on 2025-10-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmbeddingModel', '0001_initial'),
    ]

    operations = [
    ]
