# Generated by Django 5.0.9 on 2025-10-08 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmbeddingModel', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('branch', 'Branch'), ('specialization', 'Specialization'), ('client', 'Client')], max_length=20)),
                ('entity_id', models.IntegerField()),
                ('operation_type', models.CharField(choices=[('create_embedding', 'Create Embedding'), ('query', 'Query')], max_length=20)),
                ('tokens_used', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=6, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('embedding_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_stats', to='EmbeddingModel.embeddingmodel')),
            ],
            options={
                'verbose_name': 'Usage Statistics',
                'verbose_name_plural': 'Usage Statistics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'date'], name='processing__entity__4d4e7f_idx'), models.Index(fields=['date'], name='processing__date_4c8a4e_idx')],
            },
        ),
    ]
