# Generated by Django 5.0.9 on 2025-10-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_usagestats_refactor_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usagestats',
            new_name='processing__branch__efe4dd_idx',
            old_name='usage_branch_date_idx',
        ),
        migrations.RenameIndex(
            model_name='usagestats',
            new_name='processing__special_197142_idx',
            old_name='usage_spec_date_idx',
        ),
        migrations.RenameIndex(
            model_name='usagestats',
            new_name='processing__client__d5e589_idx',
            old_name='usage_client_date_idx',
        ),
    ]
