# Generated by Django 5.0.9 on 2025-10-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_rename_usage_branch_date_idx_processing__branch__efe4dd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagestats',
            name='operation_type',
            field=models.CharField(choices=[('create_embedding', 'Create Embedding'), ('query', 'Query'), ('scan_qr', 'Scan QR'), ('rag_chat', 'RAG Chat')], max_length=20),
        ),
    ]
