# Generated by Django 5.2.6 on 2025-10-01 12:59

from MASTER.clients import models as clients_models
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmbeddingModel', '0001_initial'),
        ('branches', '__first__'),
        ('specializations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('max_storage_mb', models.IntegerField(default=1000)),
                ('max_documents', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='branches.Branch')),
                ('embedding_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='EmbeddingModel.EmbeddingModel')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='specializations.Specialization')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='clients/%Y/%m/', validators=[clients_models.validate_file_size])),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('csv', 'CSV'), ('xml', 'XML'), ('json', 'JSON'), ('docx', 'Word')], max_length=10)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('chunks_count', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.ClientProfile')),
            ],
            options={
                'verbose_name': 'Client Document',
                'verbose_name_plural': 'Client Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('rate_limit_per_day', models.IntegerField(default=1000)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('requests_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='clients.clientprofile')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(dimensions=3072)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='clients.ClientDocument')),
                ('embedding_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_embeddings', to='EmbeddingModel.EmbeddingModel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='clients.ClientProfile')),
            ],
            options={
                'verbose_name': 'Client Embedding',
                'verbose_name_plural': 'Client Embeddings',
                'indexes': [models.Index(fields=['client'], name='clients_cli_client__5a90c8_idx'), models.Index(fields=['embedding_model'], name='clients_cli_embeddi_01cc42_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['client', 'is_processed'], name='clients_cli_client__8a4fbf_idx'),
        ),
    ]
