# Generated by Django 5.0.9 on 2025-10-08 06:30

import MASTER.clients.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('specializations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=MASTER.clients.models.generate_api_key, max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('rate_limit_per_day', models.IntegerField(default=10000)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client API Key',
                'verbose_name_plural': 'Client API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientembedding',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientembedding',
            name='document',
        ),
        migrations.RemoveField(
            model_name='clientembedding',
            name='embedding_model',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='embedding_model',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='clientdocument',
            name='clients_cli_client__8a4fbf_idx',
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='file',
            field=models.FileField(upload_to='clients/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('csv', 'CSV'), ('json', 'JSON'), ('docx', 'Word')], max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='specializations.specialization'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientapikey',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='clients.client'),
        ),
        migrations.DeleteModel(
            name='APIKey',
        ),
        migrations.DeleteModel(
            name='ClientEmbedding',
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.AddIndex(
            model_name='clientapikey',
            index=models.Index(fields=['key', 'is_active'], name='clients_cli_key_bf5413_idx'),
        ),
    ]
