# Generated by Django 5.0.9 on 2025-10-08 06:51

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmbeddingModel', '0001_initial'),
        ('clients', '0002_client_clientapikey_remove_apikey_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(dimensions=3072)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='clients.client')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='clients.clientdocument')),
                ('embedding_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_embeddings', to='EmbeddingModel.embeddingmodel')),
            ],
            options={
                'verbose_name': 'Client Embedding',
                'verbose_name_plural': 'Client Embeddings',
                'indexes': [models.Index(fields=['client'], name='clients_cli_client__5a90c8_idx'), models.Index(fields=['embedding_model'], name='clients_cli_embeddi_01cc42_idx')],
            },
        ),
    ]
