# Generated by Django 5.0.9 on 2025-10-08 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('nodejs', 'Node.js'), ('php', 'PHP'), ('curl', 'cURL')], default='python', max_length=20)),
                ('integration_type', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('web', 'Web'), ('mobile', 'Mobile')], default='web', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_config', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client API Config',
                'verbose_name_plural': 'Client API Configs',
                'ordering': ['-created_at'],
            },
        ),
    ]
