# Generated by Django 5.0.9 on 2025-10-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientapiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
