# Generated by Django 5.0.9 on 2025-10-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_add_vector_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='custom_system_prompt',
            field=models.TextField(blank=True, help_text="Custom system prompt for this client's AI assistant. Leave empty to use default."),
        ),
    ]
