# Generated by Django 5.0.14 on 2025-10-14 07:16

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_custom_system_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientembedding',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='clientembedding',
            name='vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
