# Generated by Django 5.0.14 on 2025-10-17 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_make_vector_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientZeroConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('starting', 'Starting'), ('running', 'Running'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('error', 'Error')], default='disabled', max_length=16)),
                ('image', models.CharField(blank=True, default='', help_text='Optional prebuilt image tag, e.g. ghcr.io/mail-0/zero:staging', max_length=200)),
                ('repo_url', models.CharField(default='https://github.com/Mail-0/Zero', max_length=300)),
                ('repo_branch', models.CharField(default='staging', max_length=64)),
                ('subdomain', models.CharField(blank=True, help_text='Optional subdomain for routing (e.g. client1)', max_length=100)),
                ('domain', models.CharField(blank=True, help_text='Root domain for routing (e.g. example.com)', max_length=200)),
                ('host_port', models.PositiveIntegerField(blank=True, help_text='Host port mapped to the Zero container (auto-assigned if empty)', null=True)),
                ('container_name', models.CharField(blank=True, max_length=150)),
                ('container_id', models.CharField(blank=True, max_length=100)),
                ('db_name', models.CharField(blank=True, max_length=100)),
                ('db_user', models.CharField(blank=True, max_length=100)),
                ('db_password', models.CharField(blank=True, max_length=200)),
                ('db_host', models.CharField(blank=True, default='postgres', max_length=200)),
                ('db_port', models.PositiveIntegerField(default=5432)),
                ('better_auth_secret', models.CharField(blank=True, max_length=200)),
                ('google_client_id', models.CharField(blank=True, max_length=300)),
                ('google_client_secret', models.CharField(blank=True, max_length=300)),
                ('autumn_secret_key', models.CharField(blank=True, max_length=300)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=200)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=200)),
                ('twilio_phone_number', models.CharField(blank=True, max_length=50)),
                ('drop_agent_tables', models.BooleanField(default=False)),
                ('thread_sync_max_count', models.PositiveIntegerField(default=500)),
                ('thread_sync_loop', models.BooleanField(default=True)),
                ('custom_env', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zero_config', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Zero Config',
                'verbose_name_plural': 'Client Zero Configs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='clients_cli_status_144818_idx')],
            },
        ),
    ]
