# Generated by Django 5.0.9 on 2025-10-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_clientzeroconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('medical', 'Medical'), ('retail', 'Retail')], default='generic', help_text='Type of client business for specific features', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Feature flags for this client. Example for restaurant:\n        {\n            "menu_chat": true,\n            "allergens": true,\n            "calories": true,\n            "table_ordering": true,\n            "multilingual": true,\n            "photo_recognition": true,\n            "pos_webhook": "https://restaurant.com/api/orders",\n            "payment_enabled": false\n        }\n        '),
        ),
    ]
