# Generated by Django 4.2.7 on 2025-10-24 10:49

from django.db import migrations, models
import django.db.models.deletion

# Міграція для додавання моделей WhatsApp інтеграції для ресторанів:
# - Table: столики з QR-кодами для сканування клієнтами
# - ConversationHistory: історія розмов WhatsApp з клієнтами
# - TableStatistics: агрегована статистика по столиках за день


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_client_type_client_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(help_text='Номер столика (наприклад: "5", "VIP-1", "Тераса-3")', max_length=20, verbose_name='Номер столика')),
                ('qr_code', models.ImageField(blank=True, help_text='QR-код для сканування клієнтами', null=True, upload_to='tables/qr_codes/', verbose_name='QR-код')),
                ('is_active', models.BooleanField(default=True, help_text='Чи активний столик для замовлень', verbose_name='Активний')),
                ('notes', models.TextField(blank=True, help_text='Додаткові примітки про столик', verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='clients.client', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
                'ordering': ['restaurant', 'table_number'],
            },
        ),
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(help_text='Номер телефону клієнта в форматі +380671234567', max_length=20, verbose_name='Телефон клієнта')),
                ('messages', models.JSONField(default=list, help_text='Список повідомлень у форматі JSON', verbose_name='Повідомлення')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Початок розмови')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Час завершення розмови (null якщо активна)', null=True, verbose_name='Кінець розмови')),
                ('is_active', models.BooleanField(default=True, help_text='Чи активна розмова (менше 24 годин без повідомлень)', verbose_name='Активна')),
                ('total_messages', models.IntegerField(default=0, help_text='Кількість повідомлень в розмові', verbose_name='Всього повідомлень')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='clients.client', verbose_name='Ресторан')),
                ('table', models.ForeignKey(blank=True, help_text='Столик, з якого почалася розмова (може бути пустим)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='clients.table', verbose_name='Столик')),
            ],
            options={
                'verbose_name': 'Історія розмови',
                'verbose_name_plural': 'Історії розмов',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TableStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата для якої збирається статистика', verbose_name='Дата')),
                ('total_conversations', models.IntegerField(default=0, help_text='Кількість розмов за день', verbose_name='Всього розмов')),
                ('total_messages', models.IntegerField(default=0, help_text='Кількість повідомлень за день', verbose_name='Всього повідомлень')),
                ('total_duration_hours', models.FloatField(default=0.0, help_text='Загальна тривалість розмов в годинах', verbose_name='Години діалогів')),
                ('unique_customers', models.IntegerField(default=0, help_text='Кількість унікальних клієнтів за день', verbose_name='Унікальні клієнти')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='clients.table', verbose_name='Столик')),
            ],
            options={
                'verbose_name': 'Статистика столика',
                'verbose_name_plural': 'Статистика столиків',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['table', 'date'], name='clients_tab_table_i_04b068_idx'), models.Index(fields=['date'], name='clients_tab_date_6d7015_idx')],
                'unique_together': {('table', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['restaurant', 'is_active'], name='clients_tab_restaur_4361b2_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['table_number'], name='clients_tab_table_n_976af1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('restaurant', 'table_number')},
        ),
        migrations.AddIndex(
            model_name='conversationhistory',
            index=models.Index(fields=['restaurant', 'customer_phone'], name='clients_con_restaur_6d90a7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationhistory',
            index=models.Index(fields=['table'], name='clients_con_table_i_a54aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationhistory',
            index=models.Index(fields=['started_at'], name='clients_con_started_8a176f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationhistory',
            index=models.Index(fields=['is_active'], name='clients_con_is_acti_32897b_idx'),
        ),
    ]
