# Generated by Django 5.0.9 on 2025-10-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_add_whatsapp_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, help_text='Логотип ресторану для QR-кодів', null=True, upload_to='clients/logos/', verbose_name='Логотип'),
        ),
    ]
