# Generated by Django 4.2.7 on 2025-10-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_add_logo_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='table',
            name='restaurant',
        ),
        migrations.AlterUniqueTogether(
            name='tablestatistics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tablestatistics',
            name='table',
        ),
        migrations.DeleteModel(
            name='ConversationHistory',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='TableStatistics',
        ),
    ]
