# Generated by Django 5.0.9 on 2025-12-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('clients', '0013_alter_table_unique_together_remove_table_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='branch',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='clients',
                to='branches.branch'
            ),
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='api_key',
            field=models.CharField(default='', editable=False, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='specialization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='clients',
                to='specializations.specialization'
            ),
        ),
    ]

