# Generated by Django 5.0.9 on 2025-12-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_add_branch_tag_description_api_key_to_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]

