# Generated by Django 5.0.9 on 2025-10-17 11:19

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmbeddingModel', '0001_initial'),
        ('clients', '0010_client_client_type_client_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_translations', models.JSONField(blank=True, default=dict, help_text='{"en": "Appetizers", "uk": "Закуски"}')),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'client_type': 'restaurant'}, on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='clients.client')),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('client', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_translations', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField()),
                ('description_translations', models.JSONField(blank=True, default=dict)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant/menu/%Y/%m/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL if not uploading')),
                ('calories', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('proteins', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fats', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('allergens', models.JSONField(blank=True, default=list, help_text='List of allergens: ["gluten", "dairy", "nuts", "shellfish", "eggs", "soy"]')),
                ('dietary_labels', models.JSONField(blank=True, default=list, help_text='["vegetarian", "vegan", "gluten-free", "halal", "kosher"]')),
                ('ingredients', models.TextField(blank=True, help_text='Detailed ingredients list')),
                ('cooking_time', models.IntegerField(blank=True, help_text='Preparation time in minutes', null=True)),
                ('spicy_level', models.IntegerField(default=0, help_text='0-5 scale', validators=[django.core.validators.MinValueValidator(0)])),
                ('wine_pairing', models.TextField(blank=True)),
                ('chef_recommendation', models.BooleanField(default=False)),
                ('popular_item', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_until', models.TimeField(blank=True, null=True)),
                ('stock_quantity', models.IntegerField(blank=True, help_text='For limited items', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='["signature", "seasonal", "new"]')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='restaurant.menucategory')),
                ('client', models.ForeignKey(limit_choices_to={'client_type': 'restaurant'}, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='clients.client')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
                ('content', models.TextField(help_text='Combined searchable content from menu item')),
                ('language', models.CharField(default='uk', help_text='Language of the content', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_embeddings', to='EmbeddingModel.embeddingmodel')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='restaurant.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Embedding',
                'verbose_name_plural': 'Menu Item Embeddings',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_language', models.CharField(default='uk', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('pos_order_id', models.CharField(blank=True, help_text='External POS system order ID', max_length=100)),
                ('webhook_sent', models.BooleanField(default=False)),
                ('webhook_response', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_orders', to='clients.client')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='e.g., "No onions", "Extra spicy"')),
                ('modifiers', models.JSONField(blank=True, default=list, help_text='["extra cheese", "no ice"]')),
                ('is_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='restaurant.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(blank=True, help_text='e.g., "Main Hall", "Terrace", "VIP Room"', max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='restaurant/qr_codes/')),
                ('qr_code_url', models.URLField(blank=True, editable=False)),
                ('access_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'client_type': 'restaurant'}, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tables', to='clients.client')),
            ],
            options={
                'verbose_name': 'Restaurant Table',
                'verbose_name_plural': 'Restaurant Tables',
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('message', models.TextField()),
                ('language', models.CharField(default='uk', max_length=10)),
                ('context_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_chats', to='clients.client')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='restaurant.order')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='restaurant.restauranttable')),
            ],
            options={
                'verbose_name': 'Restaurant Chat',
                'verbose_name_plural': 'Restaurant Chats',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurant.restauranttable'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['client', 'is_available'], name='restaurant__client__d73fad_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_available'], name='restaurant__categor_d2e8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemembedding',
            index=models.Index(fields=['menu_item'], name='restaurant__menu_it_a0fedf_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemembedding',
            index=models.Index(fields=['language'], name='restaurant__languag_4b2d2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemembedding',
            unique_together={('menu_item', 'embedding_model', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='restauranttable',
            unique_together={('client', 'table_number')},
        ),
        migrations.AddIndex(
            model_name='restaurantchat',
            index=models.Index(fields=['session_id', 'created_at'], name='restaurant__session_464e60_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantchat',
            index=models.Index(fields=['client', 'created_at'], name='restaurant__client__19fff0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='restaurant__client__987e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['table', 'status'], name='restaurant__table_i_188116_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='restaurant__order_n_c708e0_idx'),
        ),
    ]
