# Generated by Django 5.0.9 on 2025-10-23 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_client_type_client_features'),
        ('restaurant', '0002_alter_menuitem_options_menu_menuitem_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_menu_items', to='clients.clientdocument'),
        ),
    ]
