# Generated by Django 4.2.7 on 2025-10-24 12:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_table_unique_together_remove_table_restaurant_and_more'),
        ('restaurant', '0003_menuitem_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(help_text='Customer phone number in format +380671234567', max_length=20, verbose_name='Customer Phone')),
                ('messages', models.JSONField(default=list, help_text='List of messages in JSON format', verbose_name='Messages')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Conversation Start')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Time when conversation ended (null if active)', null=True, verbose_name='Conversation End')),
                ('is_active', models.BooleanField(default=True, help_text='Whether conversation is active (less than 24 hours without messages)', verbose_name='Active')),
                ('total_messages', models.IntegerField(default=0, help_text='Number of messages in conversation', verbose_name='Total Messages')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Session ID')),
                ('language', models.CharField(default='uk', max_length=10, verbose_name='Language')),
                ('context_metadata', models.JSONField(blank=True, default=dict, verbose_name='Context Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Restaurant Conversation',
                'verbose_name_plural': 'Restaurant Conversations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TableStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for which statistics are collected', verbose_name='Date')),
                ('total_conversations', models.IntegerField(default=0, help_text='Number of conversations per day', verbose_name='Total Conversations')),
                ('total_messages', models.IntegerField(default=0, help_text='Number of messages per day', verbose_name='Total Messages')),
                ('total_duration_hours', models.FloatField(default=0.0, help_text='Total duration of conversations in hours', verbose_name='Dialog Hours')),
                ('unique_customers', models.IntegerField(default=0, help_text='Number of unique customers per day', verbose_name='Unique Customers')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Table Statistics',
                'verbose_name_plural': 'Table Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='restaurantchat',
            name='client',
        ),
        migrations.RemoveField(
            model_name='restaurantchat',
            name='order',
        ),
        migrations.RemoveField(
            model_name='restaurantchat',
            name='table',
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='access_token',
            field=models.CharField(editable=False, max_length=64, unique=True, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='capacity',
            field=models.IntegerField(help_text='Number of seats at the table', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='client',
            field=models.ForeignKey(limit_choices_to={'client_type': 'restaurant'}, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tables', to='clients.client', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name for the table', max_length=100, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the table is available for orders', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='is_occupied',
            field=models.BooleanField(default=False, help_text='Whether the table is currently occupied', verbose_name='Occupied'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='location',
            field=models.CharField(blank=True, help_text='e.g., "Main Hall", "Terrace", "VIP Room"', max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the table', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code for customer scanning', null=True, upload_to='restaurant/qr_codes/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='qr_code_url',
            field=models.URLField(blank=True, editable=False, verbose_name='QR Code URL'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='table_number',
            field=models.CharField(help_text='Table number (e.g., "5", "VIP-1", "Terrace-3")', max_length=20, verbose_name='Table Number'),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='restauranttable',
            index=models.Index(fields=['client', 'is_active'], name='restaurant__client__8ea66d_idx'),
        ),
        migrations.AddIndex(
            model_name='restauranttable',
            index=models.Index(fields=['table_number'], name='restaurant__table_n_d8a141_idx'),
        ),
        migrations.DeleteModel(
            name='RestaurantChat',
        ),
        migrations.AddField(
            model_name='tablestatistics',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='restaurant.restauranttable', verbose_name='Table'),
        ),
        migrations.AddField(
            model_name='restaurantconversation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_conversations', to='clients.client', verbose_name='Restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantconversation',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Table where the conversation started (can be empty)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='restaurant.restauranttable', verbose_name='Table'),
        ),
        migrations.AddIndex(
            model_name='tablestatistics',
            index=models.Index(fields=['table', 'date'], name='restaurant__table_i_0acc17_idx'),
        ),
        migrations.AddIndex(
            model_name='tablestatistics',
            index=models.Index(fields=['date'], name='restaurant__date_e8a7d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tablestatistics',
            unique_together={('table', 'date')},
        ),
        migrations.AddIndex(
            model_name='restaurantconversation',
            index=models.Index(fields=['client', 'customer_phone'], name='restaurant__client__067126_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantconversation',
            index=models.Index(fields=['table'], name='restaurant__table_i_f1be42_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantconversation',
            index=models.Index(fields=['started_at'], name='restaurant__started_c485aa_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantconversation',
            index=models.Index(fields=['is_active'], name='restaurant__is_acti_c03aea_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantconversation',
            index=models.Index(fields=['session_id', 'created_at'], name='restaurant__session_e1254d_idx'),
        ),
    ]
