# Generated by Django 5.0.9 on 2025-10-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurantconversation_tablestatistics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
