from datetime import datetime, timezone as tz
from typing import Optional

def now() -> datetime: ...
def is_aware(value: datetime) -> bool: ...
def is_naive(value: datetime) -> bool: ...
def make_aware(value: datetime, timezone: Optional[tz] = None) -> datetime: ...
def make_naive(value: datetime, timezone: Optional[tz] = None) -> datetime: ...
def get_current_timezone() -> Optional[tz]: ...
def get_default_timezone() -> tz: ...
def activate(timezone: tz) -> None: ...
def deactivate() -> None: ...
def override(timezone: tz) -> None: ...
